# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/

language: en
pipeline: pretrained_embeddings_spacy

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: "FallbackPolicy"
    nlu_threshold: 0.35
    core_threshold: 0.30
    fallback_action_name: "action_default_fallback"
