# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/

language: en
pipeline: 
  - name: "SpacyNLP"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "RegexFeaturizer"
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "SklearnIntentClassifier"
  - name: "ner_duckling_http"
    url: "http://0.0.0.0:8000"
    dimensions: ["time","number"]
    locale: "en_GB"
    timezone: "Asia/Mumbai"


# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: FormPolicy
  
